MODEL:
  NAME: EfficientSAM3_Text_L
  BACKBONE: MobileCLIP2-L
  PRETRAINED: ''
  RESUME: ''

TRAIN:
  START_EPOCH: 0
  EPOCHS: 100
  WARMUP_EPOCHS: 10
  WEIGHT_DECAY: 0.05
  BASE_LR: 5e-3
  WARMUP_LR: 1e-6
  MIN_LR: 5e-6
  CLIP_GRAD: 1.0
  AUTO_RESUME: True
  ACCUMULATION_STEPS: 2
  USE_CHECKPOINT: False
  LAYER_LR_DECAY: 0.9
  EVAL_BN_WHEN_TRAINING: False
  FIND_UNUSED_PARAMETERS: True

  LR_SCHEDULER:
    NAME: 'cosine'
    DECAY_EPOCHS: 30
    DECAY_RATE: 0.1

  OPTIMIZER:
    NAME: 'adamw'
    EPS: 1e-8
    BETAS: (0.9, 0.999)
    MOMENTUM: 0.9

AMP_ENABLE: True
OUTPUT: output/stage1_text/mobileclip_l
TAG: text_ctx16
SAVE_FREQ: 5
PRINT_FREQ: 100
SEED: 0
EVAL_MODE: False
THROUGHPUT_MODE: False
LOCAL_RANK: 0

DATA:
  IMG_SIZE: 1008
  DATASET: text_annotations
  DATA_PATH: data/text_annotations_combined_5_dataset.json
  BATCH_SIZE: 64
  NUM_WORKERS: 8

DISTILL:
  ENABLED: True
  ENCODER_ONLY: True
  EMBED_DIM: 256
  EMBED_SIZE: 0
  NUM_EMBED: 16
  PIXEL_WISE: 1.0
  CHANNEL_WISE: 0.0
  CORRELATION: 0.0
  COSINE: 2.0
  TEACHER_EMBED_PATH: 'output/stage1_text_teacher/embeddings_ctx16/'
  SAVE_TEACHER_EMBED: False
  NO_RAND: True
  MAX_ALLOWED_PROMPTS: -1
  MASK_PAD_TOKENS: True
  CONTEXT_LENGTH: 16
  POS_EMBED_TABLE_SIZE: 16
  CONSISTENCY_LOSS: 0.05
